extends: metric
message: '%s'
link: https://en.wikipedia.org/wiki/Flesch%E2%80%93Kincaid_readability_tests

formula: |
  206.835 - (1.015 * (words / sentences)) - (84.6 * (syllables / words))

condition: "< 70"
